[0m11:42:31.831084 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4273eecb80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4274d49bd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4274d49b70>]}


============================== 11:42:31.832939 | a169ba76-b86a-4858-9030-db067a98bc54 ==============================
[0m11:42:31.832939 [info ] [MainThread]: Running with dbt=1.9.2
[0m11:42:31.833415 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/ricky/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m11:42:31.833744 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/ricky/git/medicare-analytics/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:42:31.834302 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.04308829, "process_in_blocks": "304", "process_kernel_time": 0.03085, "process_mem_max_rss": "86284", "process_out_blocks": "8", "process_user_time": 0.843236}
[0m11:42:31.834595 [debug] [MainThread]: Command `dbt run` failed at 11:42:31.834528 after 0.04 seconds
[0m11:42:31.834836 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4273eecb80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4274d4a290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4274d49bd0>]}
[0m11:42:31.835089 [debug] [MainThread]: Flushing usage events
[0m11:42:32.033068 [debug] [MainThread]: An error was encountered while trying to flush usage events
